<?php

return Symfony\CS\Config\Config::create()
    ->level(Symfony\CS\FixerInterface::NONE_LEVEL)
    ->fixers(
        [
            // Symfony level
            'psr0',
            'encoding',
            'short_tag',
            'braces',
            'elseif',
            'eof_ending',
            'function_declaration',
            'indentation',
            'line_after_namespace',
            'linefeed',
            'lowercase_constants',
            'lowercase_keywords',
            'multiple_use',
            'php_closing_tag',
            'trailing_spaces',
            'visibility',
            //'concat_without_spaces',
            'duplicate_semicolon',
            'extra_empty_lines',
            'include',
            'multiline_array_trailing_comma',
            'namespace_no_leading_whitespace',
            'new_with_braces',
            'object_operator',
            'operators_spaces',
            'phpdoc_params',
            'remove_lines_between_uses',
            'return',
            'single_array_no_trailing_comma',
            'spaces_before_semicolon',
            'spaces_cast',
            'standardize_not_equal',
            'ternary_spaces',
            'unused_use',
            'whitespacy_lines',
            // Custom
            'ordered_use',
            'short_array_syntax',
            'concat_with_spaces',
        ]
    )
    ;
